version: '2'
services:
    zoneminder:
        container_name: zoneminder
        restart: always
        build: .
        ports:
            - 80:80
            - 443:443
        links:
            - mysql
    mysql:
        container_name: zoneminder_mysql
        restart: always
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=ilikerandompasswords
            - MYSQL_DATABASE=zm
            - MYSQL_USER=zoneminder
            - MYSQL_PASSWORD=zoneminder
        volumes:
            - ./mysql-data:/var/lib/mysql
        depends_on:
            - phpmyadmin
    phpmyadmin:
        restart: always
        image: konjak/phpmyadmin
        ports:
            - 8000:80
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=ilikerandompasswords
networks:
    default:
        driver: bridge
